###
GET http://localhost:6666/users/6564ba84-1304-11ed-94dc-ab5bc5caa4d6
Content-Type: application/json

###
GET http://localhost:6666/users/
Content-Type: application/json

###
POST http://localhost:6666/users
Content-Type: application/json

{
  "lastname": "Hardly",
  "firstname": "Testing",
  "age": 666
}

###
DELETE http://localhost:6666/users/792823c0-85f8-4aab-bd4b-e497aa030946
Content-Type: application/json

###
PUT http://localhost:6666/users/6564dee2-1304-11ed-94dc-ab5bc5caa4d6
Content-Type: application/json

{
  "lastname": "Shishke",
  "firstname": "Vlad",
  "age": 57
}

###
GET http://localhost:6666/users/6564ba84-1304-11ed-94dc-ab5bc5caa4d6
Content-Type: application/json
